spring:
  application:
    name: API PRODUCTS
  datasource:
    url: jdbc:h2:mem:productsdb
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2